services:
  - type: web
    name: advanced-pdf-rag-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m streamlit run app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: MODEL_NAME
        value: llama-3.1-8b-instant
      - key: CHROMA_DB_DIR
        value: /tmp/chroma_db